# Generated by Django 4.2.5 on 2023-10-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterials_suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialsupplier',
            name='total',
        ),
    ]
