# Generated by Django 4.2.5 on 2023-10-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages='sorry this Raw Material exists before', max_length=200, unique=True)),
                ('quantity', models.IntegerField(error_messages={'null': 'insert the quantity please'})),
                ('price', models.DecimalField(decimal_places=2, error_messages={'null': 'insert the price please'}, max_digits=9)),
                ('details', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'Raw_Material',
            },
        ),
    ]
